import Head from 'next/head'
import Image from 'next/image'
import { Html } from './styles';
import {useEffect} from 'react';

export function Parallax(){
  useEffect(()=>{
    document.addEventListener("mousemove", parallax);
  });

  function parallax(e:any){
    this.querySelectorAll('.layer').forEach(layer => {
      const speed = layer.getAttribute('data-speed');
      const x = (window.innerWidth - e.pageX*speed)/100
      const y = (window.innerWidth - e.pageY*speed)/100
      layer.style.transform = `translateX(${x}px) translateY(${y}px)`
    })};

  return (
    <Html>
      <Head>
        <title>Plataforma-Ead</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <body>
        <section>
          <img src='/images/parallax/1.png' data-speed='-5' className='layer'  alt=''/>
          <img src='/images/parallax/2.png' data-speed='5' className='layer'  alt=''/>
          <img src='/images/parallax/3.png' data-speed='2' className='layer'  alt=''/>
          <img src='/images/parallax/4.png' data-speed='6' className='layer'  alt=''/>
          <img src='/images/parallax/5.png' data-speed='8' className='layer'  alt=''/>
          <img src='/images/parallax/6.png' data-speed='-2' className='layer'  alt=''/>
          <img src='/images/parallax/7.png' data-speed='4' className='layer'  alt=''/>
          <img src='/images/parallax/8.png' data-speed='-9' className='layer'  alt=''/>
          <img src='/images/parallax/9.png' data-speed='6' className='layer'  alt=''/>
          <img src='/images/parallax/10.png' data-speed='-7' className='layer'  alt=''/>
          <img src='/images/parallax/11.png' data-speed='-5' className='layer'  alt=''/>
          <img src='/images/parallax/12.png' data-speed='5' className='layer'  alt=''/>
          
          
          <h2 id='gradient' data-speed='2' className='layer'>LogoMarca</h2>
        </section>
      </body>
    </Html>
  )
}